### ISSUE TITLE
mkdir Windows Problem

### ISSUE THREAD

**Issue by carloszimm** [mostjs-community/package-seed#1]
Hey, @hoichi!

While messing around with the package-seed, I noticed a small problem in the scripts regarding Windows operating system.
The command mkdir -p dist in build:umd doesn't work as you intended in Windows. In fact, the way it is right now it creates two directories '-p' and 'dist'.

**Comment by hoichi** [comment]
Hey @cezl, thanks for the heads up. Funny thing is, -p doesn't seem to be required at any platform, so I think I’m gonna remove it (in a day or so, one hopes).

**Comment by carloszimm** [comment]
No problem, @hoichi :)
It turns out the -p option is valid only for Unix-like systems
Still, I think you should consider removing not only the -p option but the mkdir command itself.
I've tested in my environment (not tested on Linux distros), and it seems that rollup automatically creates a dist folder if there isn't one

**Comment by hoichi** [comment]
Fixed. I’ve also removed traces of the name of the package I’ve made this package from :)

Tested on Windows 10, on an oldish Linux Mint (based on Ubuntu 16), and on even older MacOS, so let’s hope it’s ok.

**Comment by carloszimm** [comment]
awesome (:
